# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_Fitness.ui'
#
# Created: Wed Jun  5 10:59:52 2019
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1260, 1000)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1440))
        MainWindow.setStyleSheet("border-image: url(:/pic/AIFIT-diban.jpg);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(670, 527, 480, 298))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("border-image: url(:/pic/DZSB-di2.png);")
        self.textBrowser.setObjectName("textBrowser")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 251, 111))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border-image: url(:/pic/AIFIT-Logo.png);")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(203, 854, 190, 55))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("border-image: url(:/pic/BZDZ.png);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(423, 854, 190, 55))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("border-image: url(:/pic/YHSP.png);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 150, 480, 333))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("\n"
"border-image: url(:/pic/BZDZ-di.png);")
        self.label_3.setText("")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(110, 500, 480, 333))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.label_4.setFont(font)
        self.label_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setStyleSheet("\n"
"border-image: url(:/pic/YHSP-di.png);")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(670, 150, 480, 333))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-image: url(:/pic/SPCJ-di.png);\n"
"")
        self.label_5.setText("")
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(674, 500, 470, 34))
        self.comboBox.setStyleSheet("border-image: url(:/pic/round1.png);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(643, 854, 190, 55))
        self.pushButton_2.setStyleSheet("border-image: url(:/pic/SPCJ.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(873, 854, 201, 55))
        self.pushButton_3.setStyleSheet("border-image: url(:/pic/DZSB.png);")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(890, 870, 20, 22))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.textBrowser_2 = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_2.setGeometry(QtCore.QRect(670, 530, 480, 298))
        self.textBrowser_2.setStyleSheet("border-image: url(:/pic/DZSB-di.png);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(676, 640, 466, 23))
        self.progressBar.setMaximum(28)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.hide()

        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(910, 60, 98, 27))
        self.pushButton.setStyleSheet("border-image: url(:/pic/DZSB-di2.png);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(910, 100, 98, 27))
        self.pushButton_6.setStyleSheet("border-image: url(:/pic/DZSB-di2.png);")
        self.pushButton_6.setObjectName("pushButton_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_3.clicked.connect(self.textBrowser.clear)
        self.pushButton_3.clicked.connect(self.textBrowser_2.hide)
        self.pushButton_3.clicked.connect(self.progressBar.show)

        self.checkBox.stateChanged.connect(MainWindow.Skip_Fra)
        self.pushButton_2.clicked.connect(MainWindow.Camera_Start)
        self.pushButton_3.clicked.connect(MainWindow.Pose_Start)
        self.pushButton_4.clicked.connect(MainWindow.videoprocessing)
        self.pushButton_5.clicked.connect(MainWindow.videoprocessing2)
        self.pushButton.clicked.connect(MainWindow.Add_CoachVideo)
        self.pushButton_6.clicked.connect(MainWindow.Add_CoachPara)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FitNess Project Display"))
        self.comboBox.setItemText(0, _translate("MainWindow", ">>>>>>>>>>>>>>>>>>>>>>>>> [教练A] <<<<<<<<<<<<<<<<<<<<<<<"))
        self.comboBox.setItemText(1, _translate("MainWindow", ">>>>>>>>>>>>>>>>>>>>>>>>> [教练B] <<<<<<<<<<<<<<<<<<<<<<<"))
        self.pushButton.setText(_translate("MainWindow", "添加视频库"))
        self.pushButton_6.setText(_translate("MainWindow", "添加教练参数"))

import configpic
